### ISSUE TITLE
Add Vimeo to CSP

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#101]
The Vimeo player onebox is blocked from loading due to CSP

**Comment by flamingspaz** [comment]
pr at https://github.com/mozilla/discourse.mozilla.org/pull/6

**Comment by grahamperrin** [comment]
Fix confirmed, thanks. AMO now appears to spin correctly with the Washing Machine extension at https://discourse.mozilla.org/t/-/14591/7?u=grahamperrin `:-)`
