### ISSUE TITLE
Set additional email addresses from IAM

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#106]
Upstream discussion: https://meta.discourse.org/t/additional-email-support/59847

Using the additional emails received from IAM, add them to the `user_emails` table.

**Comment by LeoMcA** [comment]
Currently, the Management API only returns LDAP aliases, in the `emails`, `email_alias` and `email_aliases` attributes.

The Person API returns nothing.

And the Mozillians API returns contact identities in the `alternate_emails` attribute.

@gdestuynder, can I rely on those attributes sticking around in the management API?

@andrewkrug, it'd be great to have both LDAP aliases and Mozillians alternate contact identities in one field in the Person API. Is the ETA on that long enough that fetching these from the Mozillians API for the time being is worth it?

@akatsoulas can I rely on the `alternate_emails` attribute sticking around for a while?

**Comment by akatsoulas** [comment]
@LeoMcA the mozillians.org API won't be changing any time soon.

**Comment by hmitsch** [comment]
@LeoMcA if I remember correctly, the Person API had to be disabled before the holiday break.
@andrewkrug can probably share more light into the current situation.

Also, if there is scope to be added to the next sprint, please let me know. 😄

**Comment by andrewkrug** [comment]
We do have a field in the userprofile that's slated for alternate verified emails but it's currently not being published all the time.  There is some work to be done in the mozillians.org CIS publisher.  It would probably be a good time to ensure we're sending all the data the should exist in the profile and sending "full" profiles.

**Comment by gdestuynder** [comment]
> Currently, the Management API only returns LDAP aliases, in the emails, email_alias and email_aliases attributes.
> @gdestuynder, can I rely on those attributes sticking around in the management API?

Not in the longer term as `email_aliases` are basically a custom work-around. PersonAPI would be the more reliable way - granted that data gets published as per andrew's post above *and* that LDAP gets a CIS publisher in addition to that

**Comment by LeoMcA** [comment]
Done in https://github.com/mozilla/discourse-mozilla-iam/commit/46fa806fa1f82f8901d993cdccdbfab902baedcf, deployed to staging
