### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#116]
Request: https://discourse.mozilla.org/t/mozillas-discourse-customizations/1249/13?u=leo

This is a relatively good first bug. Work would be done in the [discourse-mozilla-theme repo](https://github.com/mozilla/discourse-mozilla-theme).

**Comment by meinfr13nd** [comment]
I'd like to make the dark theme for Mozilla Discourse. Is that something that is still needed?

**Comment by LeoMcA** [comment]
Hey @meinfr13nd,

Absolutely! We've got a number of users who'd love to use a dark colour scheme.

If you've never developed Discourse themes before, you might find the following posts from upstream helpful:

https://meta.discourse.org/t/beginners-guide-to-using-discourse-themes/91966
https://meta.discourse.org/t/how-to-develop-custom-themes/60848

And there's also https://theme-creator.discourse.org/ if you don't want to set up a local instance.

If you do, I'd suggest also installing the [discourse-style-guide plugin](https://meta.discourse.org/t/the-official-discourse-styleguide-plugin/67405) to see how your changes affect various aspects of the UI.

If you can achieve a :ok_hand: result from just editing the colour scheme, go ahead and fork and PR [`discourse-mozilla-theme`](https://github.com/mozilla/discourse-mozilla-theme).

But if you need to edit any other CSS, then I think the best way of implementing this is as a separate theme which uses [`discourse-mozilla-theme`](https://github.com/mozilla/discourse-mozilla-theme) as a component (so inherits everything from that theme), and overrides enough to make things dark. :new_moon: So I've created https://github.com/mozilla/discourse-mozilla-theme-dark for you to fork and PR to, in that case.

Let me know if you have any questions :smile:

**Comment by LeoMcA** [comment]
Ooh, also, if you can stick to colours in https://protocol.mozilla.org/fundamentals/color.html that would be brilliant!

**Comment by m-branson** [comment]
Thanks for your interest in helping here @meinfr13nd! 

I echo @LeoMcA's notes above and have a UX request as well: let's be sure to make color choices as accessibility friendly as possible. I agree with @LeoMcA that we should be following the [Protocol](https://protocol.mozilla.org/fundamentals/color.html) design system as much as possible as this is a Mozilla branded entity. In addition, the [Photon](https://design.firefox.com/photon/welcome.html) design system has some good 'rules of thumb' with regard to [color use and contrast](https://design.firefox.com/photon/visuals/color.html) on dark or colored backgrounds.

I'm available for a ping here if any specific questions come up. :)

**Comment by LeoMcA** [comment]
@meinfr13nd I presume you're not working on this any more? No worries if you're not, I just want to update the status of the ticket. If you got stuck and want to work on it again, let me know and I'm happy to help. :smiley:

**Comment by LeoMcA** [comment]
I spent some time last week on this, it's now available to try by going to [your preferences](https://discourse.mozilla.org/my/preferences/interface) and selecting "moz://a beta dark" from the "Theme" dropdown.

![Screen Shot 2019-07-29 at 13 14 55](https://user-images.githubusercontent.com/755354/62047733-1a748280-b203-11e9-89cf-5e29f1edd631.png)
