### ISSUE TITLE
Logging in using GitHub with different primary e-mail address offers to create new account

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/discourse#132]
I have different primary e-mail address for GitHub than for my LDAP and Mozillians account. However I have the GitHub account connected to my Mozillians profile. When I click "Log In" in Discourse and use GitHub login, I am offerred to create a new account. sso.mozilla.com recognizes my identity correctly.

STR:
0. Have differrent primary e-mail address for GitHub than for Mozillians.
1. Go to sso.mozilla.com and sign out.
2. Go to discourse.mozilla.org and click Log In.
3. Choose GitHub log in.

After you log in with GitHub, you see a modal JavaScript window offering to create new account in Discourse. Instead Discourse should correctly recognize me based on the Mozillians account associated with the GitHub account.

**Comment by LeoMcA** [comment]
With the way that IAM is currently designed, you can't - you can only use your LDAP account to log in. If you update your GitHub email address to match your LDAP address you won't be allowed to log in with GitHub.

**Comment by MikkCZ** [comment]
Should I file a report in https://github.com/mozilla-iam/mozilla-iam/issues, or is the use case already covered in an existing ticket?

**Comment by LeoMcA** [comment]
There's no ticket I know of which covers allowing users to log in with two different providers (e.g. LDAP and GitHub) with different email addresses, but resulting in the same account.

> If you update your GitHub email address to match your LDAP address you won't be allowed to log in with GitHub.

Roughly this is covered in https://github.com/mozilla-iam/auth0-deploy/issues/195

**Comment by MikkCZ** [comment]
I have created a ticket (wow, with a number 2 times 💯 ) to allow linking provider logins with different email addresses. Feel free to reword it if my explanation there is not clear.
