### ISSUE TITLE
login error when using container tabs

### ISSUE THREAD

**Issue by syam3526** [mozilla/discourse#136]
Cannot login to discourse when using container tabs.

https://mozilla.slack.com/files/UB4BKFKCY/FB82RGH1D/error.png

**Steps to reproduce:**

1. create a container tab (i use a tab named mozilla for all my mozilla stuff)
2. login to sso using fxa .
3. goto to discourse. 
4. try to login to discourse using the same container tab. 
5. getting error 

> Sorry, There was an error authorizing your account. Perhaps you didnt approve authorization?

**Expected Result:**
All the other i am logins work perfectly with container tabs except discourse. 
Discourse is throwing a

>  "auth/failure?message=csrf_detected&stratergy=auth0"

 in the url. 

Logged into firefox Dev edition were i am not having container tabs, used my same fxa login and it logs me in without any errors.

**Comment by TannerFilip** [comment]
It works as expected for me. Can you try in a clean profile?

**Comment by syam3526** [comment]
the problem is with container tabs. i will try to write up more precise steps to reproduce.
