### ISSUE TITLE
logo position

### ISSUE THREAD

**Issue by fstdesk** [mozilla/discourse#166]
hi,

how can i move the logo to a little right :)

thanks

**Comment by LeoMcA** [comment]
Hi @fstdesk,

Are you looking to do this on your own Discourse installation? I'm afraid I can't provide advice on that, but there should be people on https://meta.discourse.org able to help.

Or do you want to adjust the logo position on https://discourse.mozilla.org? To do that you'll have to use something like Stylish: https://userstyles.org/

**Comment by TannerFilip** [comment]
It looks like @fstdesk was directed to the right place. If this is about the Mozilla instance, just reply and we can reopen the issue to investigate!
