### ISSUE TITLE
Trivial AAL solution

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#167]
Work happening here: https://github.com/mozilla/discourse-mozilla-iam/tree/aal

Current behaviour:
- disallows login when AAL too low
- kills sessions when AAL becomes too low (e.g. user gets added to an access group) *
- <s>allows logging in with secondary emails</s>

\* currently all sessions are killed, rather than just the affected ones, [I'm working on fixing this](https://github.com/mozilla/discourse/issues/167#issuecomment-457597580)

**Comment by LeoMcA** [comment]
Things are working on staging now.

I've identified one bug where all of a user's sessions will be logged off if one of them falls below the required AAL, rather than just the session(s) which have an insufficient AAL. I'll work on fixing that next.

@viorelaioia this should be ready for QA now

**Comment by LeoMcA** [comment]
> allows logging in with secondary emails

I never fully thought this through wrt staff accounts:
- do we even want to allow login with a non staff email on a staff account? (I doubt it)
- if we do, how do we handle users being bounced in/out of staff group

So, [reverting the change for now](https://github.com/mozilla/discourse-mozilla-iam/commit/a8312f6449a844da7dc28592236d9ef556cb3c15). I'll revisit as part of the post-AAL world improvements.

**Comment by hmitsch** [comment]
> do we even want to allow login with a non staff email on a staff account? (I doubt it)

No, we do not want to allow that kind of login. The basic guideline from InfoSec is: If you are Staff, you have to use Staff LDAP (plus MFA).

Best regards,
   Henrik

**Comment by LeoMcA** [comment]
https://discourse.mozilla.org/t/mozilla-discourse-release-2019-02-27/36283
