### ISSUE TITLE
Login error when using the most secure form of authentication

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#169]
[Environment]:
Windows 10 - Firefox Nightly latest

Precondition:
Have a github account with 2FA - and an account in Discourse staging with this email
Autologin is disabled

STR:
1. Navigate to discourse staging
2. Login passwordless using the email from Preconditions -> Login error page is returned -> see issue #168
3. Click Log in button from the error page
4. From NLX window select Log in with Github
5.Enter valid login Github credentials from Preconditions

[Expected result]:
Log in should be successful

[Actual result]:

![2019-02-01_15h49_39](https://user-images.githubusercontent.com/41474886/52133315-c02aa880-2649-11e9-837c-04c6c5920940.png)

[Note]:
Browser Console warnings:
Request to access cookie or storage on “https://www.google-analytics.com/analytics.js” was blocked because it came from a tracker and content blocking is enabled. failure
Request to access cookie or storage on “https://www.google-analytics.com/r/collect?v=1&_v=j73&a=1395647161&t=pageview&_s=1&dl=https%3A%2F%2Fdiscourse-staging.production.paas.mozilla.community%2Fauth%2Ffailure%3Fmessage%3Dcsrf_detected%26strategy%3Dauth0&dr=https%3A%2F%2Fauth-dev.mozilla.auth0.com%2Flogin%3Fstate%3Dg6Fo2SBHSzFRWGhfaldsU2FvUEtYQnV1Y08zY0l1ai13cHFRSqN0aWTZMmdhRm8yU0JRZG5KTVRHUnFkRFpzT0c1U1JuWTRiSFUyUlZOVU5XZGZSVWs0VVhsT2RBo2NpZNkgUnFVbnM4ekQ1b1RzRXNqVEtBVU1oRjU1c0xmdVFzR3Y%26client%3DRqUns8zD5oTsEsjTKAUMhF55sLfuQsGv%26protocol%3Doauth2%26prompt%3Dlogin%26action%3Dlogin%26auth0Client%3DeyJuYW1lIjoib21uaWF1dGgtYXV0aDAiLCJ2ZXJzaW9uIjoiMi4wLjAifQ%253D%253D%26redirect_uri%3Dhttps%253A%252F%252Fdiscourse-staging.production.paas.mozilla.community%252Fauth%252Fauth0%252Fcallback%253Fprompt%253Dlogin%2526action%253Dlogin%26response_type%3Dcode%26scope%3Dopenid%2520name%2520email&ul=en-us&de=UTF-8&dt=Mozilla%20Discourse&sd=24-bit&sr=1920x1080&vp=1267x894&je=0&fl=32.0%20r0&_u=AACAAE

**Comment by LeoMcA** [comment]
What's happening here is:

1. Initial login with callback `A` is failing
2. User clicks login again, which succeeds with callback `B`
3. On receiving callback `B` discourse redirects to callback `A`
4. This results in a CSRF error

Where:
* callback `A` is: `/auth/auth0/callback?code=u_8wpZk4iD7pbA4I&state=8c1279418e70fd2a5caa12adad9315bd96a133140066d61f`
* callback `B` is: `/auth/auth0/callback?prompt=login&action=login&code=Y9LtgL0lsE_Pkj4z&state=766ba5fc7305cafc1aacb52dc2190f474f600300c768499a`

So I need to stop step 3 from happening. I imagine there's a cookie somewhere storing callback `A` when it errors out. It might also be a result of the `prompt=login&action=login` params being passed through.

Working on fixing it now.

**Comment by LeoMcA** [comment]
Fix deployed on staging. @rleitan can you verify please?

**Comment by rleitan** [comment]
I confirm it's fixed.
