### ISSUE TITLE
"Something went wrong processing your log in" when clicking "Go back" button from the error prompt

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#170]
[Environment]:
Windows 10 - Firefox Nightly latest

Precondition:
Autologin is disabled
Discourse staging account with LDAP (e.g. rleitan@mozilla.com)
Github account with the same email

STR:
1. Login with LDAP on Discourse staging
2. Log out
3. Click Log in button from Discourse staging
4. Select “Continue with Github” or "Continue with Google" button from NLX screen
5. Enter valid credentials-> login error (expected)
6. Click "Go Back" button and select again the login option from step 4
7. From the error screen click "Go Back" button 

[Expected result]:
The  NLX screen should be displayed

[Actual result]:
"Something went wrong processing your log in, please try again." error is displayed

[Note]:
The issue is not reproducible on Testrp links
The issue is reproducible on Discourse prod with the message: "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?"

**Comment by LeoMcA** [comment]
This is an interesting one.

I've reproduced, and the bug seems to be happening because sso.mozilla.com is appending `?prompt=login` to the go back link at step 6. Rather than redirecting to a new login attempt, discourse treats this as a proper attempt at a callback and CSRF errors out.

Working on a fix now.

**Comment by LeoMcA** [comment]
Fixed with: https://github.com/mozilla/discourse-mozilla-iam/commit/56d233d3a043f3b312936a5456a434c8f91e01a3

Deployed to staging. @rleitan can you verify please?

**Comment by rleitan** [comment]
I confirm it's fixed!
