### ISSUE TITLE
Stale session causes all sessions to be logged out

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#188]
@MichaelKohler has been reporting seemingly-random logouts for a little while, and looks like he's nailed down the conditions which lead to it:

> I've used the Reference Browser for some time, didn't have any issue
now I switched to Fenix again (used that when I told you about it the first time), and when I logged in to Discourse on Fenix I got logged out of my Desktop Nightly session
logged back in on Desktop, got logged out on Fenix
it's not 100% in-and-out, as I can log in to Discourse on Fenix and doesn't get logged out of Desktop, but still, odd

I think this is *probably* a result of one stale session logging every session out - so coming back to Fenix after a while is triggering the logout everywhere - but it could be something else.

We should fix that first, then reopen this issue if it persists.

**Comment by lissyx** [comment]
I'm hitting that on a very regular, few hours / daily basis. I'm connected using my laptop (firefox nightly) as well as on Android, Firefox Nightly. No idea if there are any stale sessions. Started circa one-two weeks ago.

**Comment by lissyx** [comment]
@LeoMcA I'm wondering in my case if I don't get disconnected from all sessions as long as I login on one device. This is very very very much painful.

**Comment by LeoMcA** [comment]
Okay, I've gone for the super fast and simple fix, by just changing the `log_out_strict` setting in Discourse (which was causing our calls to `Auth::DefaultCurrentUserProvider#log_off_user` to kill all sessions).

This also has the effect that when users click "Log out" on Discourse it only logs them out of their active session, but I think this is fine because the "Log out all" option still exists under [Recently Used Devices](https://discourse.mozilla.org/my/preferences/account).

@lissyx @MichaelKohler apologies for not doing this very easy fix sooner, I overcomplicated the issue in my mind a little. I *hope* this fixes your issues, otherwise something very weird is going on, let me know if it doesn't.

**Comment by MichaelKohler** [comment]
Thanks, will keep an eye out on this and report back if it shouldn't be fixed. :)

**Comment by lissyx** [comment]
Thanks @LeoMcA I'll keep an eye on that as well.

**Comment by MichaelKohler** [comment]
@LeoMcA looks like this is not fully solved yet, I'm getting logged out regularly still, and it seems other still have that problem: https://discourse.mozilla.org/t/i-keep-getting-logged-out-of-discourse-all-the-time/37851

**Comment by lissyx** [comment]
I can confirm, opened a link on my phone, got logged out, I logged in. Came back to the same link an hour later, logged out again. Same phone, se Firefox nightly instance.

**Comment by LeoMcA** [comment]
Okay, I'm still pretty stumped as to what's causing this, so I've deployed increased logging on prod. Every time a user gets logged off because of our IAM logic, it'll be logged.

@MichaelKohler, @lissyx next time this happens for either of you can you ping me, and I'll take a look at the logs?

**Comment by lissyx** [comment]
It happened this morning or afternoon for me. What kind of data / timestamp do you need ?

**Comment by LeoMcA** [comment]
The logging wasn't in place for your morning/afternoon logout, but should catch the next time it happens.

If you can tell me the timestamp of when it next happens, that could be helpful, but not absolutely necessary. A ping shortly after the next time it happens means I can look through the logs to see why.

**Comment by lissyx** [comment]
It just happened to me, a few seconds ago

**Comment by LeoMcA** [comment]
Thanks for letting me know - the logs show this happening for *a lot* of users, all with an identical error:

```
Killed session for user <id>: RuntimeError (Mozilla IAM: AAL not enough, user logged out
user_id: <id>, aal: 
)
```

The fact that `aal` is shown blank is *bizarre*, because it means that some of the session storage is being lost (but not all of it, because Discourse still has knowledge of what user is logged in).

I haven't been able to reproduce this locally yet, so I've increased the logging on prod to also log the full session to see if that answers any questions for me.

**Comment by lissyx** [comment]
Happens at least each time I'm on Firefox for Android Nightly. Happened just a few min ago 😕

**Comment by hmitsch** [comment]
@lissyx and @michselkohler Are you using different login methods on different devices? (Eg LDAP on Desktop, passwordless email on Nightly)

**Comment by MichaelKohler** [comment]
Nope, always using LDAP

**Comment by lissyx** [comment]
> Nope, always using LDAP

Same.

**Comment by LeoMcA** [comment]
Thankfully - *finally* - I've figured it out:

Discourse uses two cookies for storing data about a user's session: an authentication token cookie (which determines who is logged in) and a session store cookie (which holds encrypted data about a user's session). I've been storing data about a user's Mozilla IAM session within the session cookie.

Unfortunately, there's an inconsistency with the expiry dates of the cookies: the session cookie is set to clear at the end of a *browser* session, whereas the token cookie is set to expire a month from the last rotation (which happens regularly while a user is logged in). So, if the browser's session is cleared, the token cookie persists - so a user remains logged into discourse - but the session cookie is cleared - meaning the extra IAM data is also cleared, and so some users (NDA/staff) get logged out because their authentication method isn't deemed sufficiently secure.

So apologies, this bug was a result of me misunderstanding the intricacies of Discourse's session system. I'm about to post upstream to see if we can create a better system for storing long-lived data in sessions, to fix this problem.

For the time being, you should hopefully be able to mitigate this bug by enabling "restore session" in Firefox on your devices - this way the session cookie shouldn't be cleared.

**Comment by lissyx** [comment]
I do have session restore enabled, maybe it again regressed as well?

**Comment by MichaelKohler** [comment]
If I understand this correctly, Discourse sets cookies with a session lifetime, correct? Then I doubt Session Restore would restore those, though I don't know 100% sure that Session Restore doesn't restore session-lifetime cookies. Though I'd honestly expect it not to. Given that I have session restore enabled as well, I doubt this is the workaround needed here.

**Comment by LeoMcA** [comment]
Thanks for bearing with me, I've deployed my fix.

This will migrate data stored in the session cookie to the new database store, so for any sessions you have where that cookie still exists you'll remain logged in and shouldn't see this bug any more. Sessions where the cookie has been deleted will be logged out one more time and you'll have to re-authenticate, after which you shouldn't see this bug any more.

So you may see one more logout as you switch between browsers on your phone, but after that you shouldn't see it any more. I'll be occasionally checking logs to make sure of that, but do ping me if you feel like this isn't fixed.
