### ISSUE TITLE
Set up profile banner is not displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#201]
[Precondition]:
No discourse account

[STR]:
1.Open https://discourse-staging.production.paas.mozilla.community
2.Sign up with valid credentials
3.Check privacy policy checkbox and click "Link my profile" button
4.Click "Confirm and create linked account" button

[Expected result]:
The banner for set up the profile should be displayed
https://overflow.io/s/3YX3BV/?node=8aa1fd57

[Actual result]:
The banner is not displayed

[Note]:
As a workaround, you have to click on Edit button for a field to be redirected to https://people.mozilla.org/e?section=personal-info

@LeoMcA

**Comment by LeoMcA** [comment]
Fixed in https://github.com/mozilla/discourse-mozilla-iam/releases/tag/v1.2.3 and deployed to prod
