### ISSUE TITLE
User cannot create a discourse account if the Dinopark username matches an existing discourse username 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/discourse#202]
**Precondition:**
1. Have an account in Dinopark with a certain username. Make sure you don't have an account in discourse for this Dinopark account.
2. Create an account in discourse with a different email from the one in step 1, but with same username as the Dinopark account from step 1

**STR:**
1. Navigate to discourse and click "Log In / Sign Up" button
2. Enter the email from step 1, that is associated to an existing Dinopark account
3. Click the privacy checkbox
4. Click the "Yes, find and link my profile" button
5. Click "Confirm and create linked account"

**Expected:**
User should have a way to edit the username in discourse and continue with account creation

**Actual:**
Error message is displayed (See 1st screenshot below). User cannot continue with account creation. 
If repeating step 5 again, a different error message is displayed. See 2nd screenshot below.
![discourse error - duplicate username](https://user-images.githubusercontent.com/5293100/57631065-7554f100-75a7-11e9-9aed-4546d0a8a04f.png)
![discourse second error](https://user-images.githubusercontent.com/5293100/57631069-77b74b00-75a7-11e9-8b53-64981027b6e0.png)

**Comment by LeoMcA** [comment]
I can't reproduce, this, and we have [a test to ensure this doesn't happen](https://github.com/mozilla/discourse-mozilla-iam/blob/0042b26/spec/requests/users_controller_spec.rb#L44-L52):

```ruby
it "uses unique username if its taken" do
  Fabricate(:user, username: "jillbloggs")
  post "/u.json", params: create_params.merge({
    dinopark_enabled: true
  })
  expect(response.status).to eq 200
  expect(User.find(JSON.parse(response.body)["user_id"]).username).to eq "jillbloggs1"
  expect(session[:authentication]&.[](:dinopark_enabled)).to eq true
end
```

So, I think this must be the same problem as in #200:
> I wonder if we're not giving enough resources to our staging instance and if it's what causing this bug. Creating a user is a relatively intensive process, perhaps all the creation/deletion during QA is causing the server to be overloaded, and produce this weird behaviour.

@viorelaioia has this ever worked for you? First time I tried it changed my "leo" dinopark username to "leo1" because an account already existed with the "leo" username. Just want to make sure I wasn't following the STR wrong.

**Comment by viorelaioia** [comment]
@LeoMcA , I reproduced this issue every time I deleted and re-created the account, by following the STR.
I cannot reproduce it anymore though, I get same results as you (it changed my username from "viorelaioia" to "viorelaioia1"). Not sure if something has changed. 
Closing the ticket.
