### ISSUE TITLE
Your full name (optional) text is displayed under the first name+last name imported from DinoPark

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#203]
[Precondition]:
Have a DinoPark account with First Name, Last Name and Alternative name set to public

[STR]:
1.Create a discourse account with the same email address as DinoPark account
2.Link the accounts
3.Go to account's preferences

[Expected result]:
The full name should be updated from DinoPark

[Actual result]:
First name+ Last name is displayed
"your full name optional" text is displayed
![2019-05-13_17h53_44](https://user-images.githubusercontent.com/41474886/57634341-ce278800-75ad-11e9-84e6-b06a2d490f92.png)

**Comment by rleitan** [comment]
I logged this issue because it was confusing to me the label "your full name (optional)" describing the field when my full name was imported from dinopark - as I am not able to edit it through discourse.

Below is attached a screenshot with profile not linked where the default name is like the username and the user can edit through discourse
![2019-05-14_12h33_42](https://user-images.githubusercontent.com/41474886/57688020-2e1d3d80-7645-11e9-9cef-59d8a613a3bf.png)
At last, can we make the label consistent, starting with capital letter as the rest of the labels? 
@mbransn what do you think?

**Comment by mbransn** [comment]
Ah I see. @LeoMcA do we need this sub label at all? Just seems to be a holdover from non-DinoPark connected profile build?

**Comment by LeoMcA** [comment]
Nope, don't need the label, I've removed it for Dinopark-linked profiles:

![Screenshot from 2019-05-17 16-56-44](https://user-images.githubusercontent.com/755354/57940645-d68d0500-78c4-11e9-97fc-6242c8ce7fc9.png)
