### ISSUE TITLE
Better UI design

### ISSUE THREAD

**Issue by etanot** [mozilla/discourse#211]
Top-most bar occupy lots of space of the screen than other `Discourse` instances. I think, it's due to larger favicon size of `Mozilla`.

![mozilla](https://user-images.githubusercontent.com/28824347/62031796-b5effe00-b1d7-11e9-9e35-90a95d95ca53.png)

Please reduce the size of top-most bar so, more text can fit into the screen.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/DISC-23)

**Comment by LeoMcA** [comment]
Hi @finn0, you can do this yourself using something like the [Stylish](https://addons.mozilla.org/en-GB/firefox/addon/stylish/) addon for Firefox.
