### ISSUE TITLE
System assigned profile picture is displayed as profile picture after linking PMO profile

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#228]
[Precondition]:
Have a discourse account liked to people.mozilla.org account
Have a people.mozilla.org account with public profile picture

[STR]:
1.Log into https://discourse-staging.production.paas.mozilla.community/
2.Go to Preferences-Account and click "Disconnect" button
3.Click "Continue, disconnect my profile" button from the dialogue prompt
4.Go to Profile picture and select System assigned profile picture
5.Log out and log in again
6.Link your people.mozilla.org account to your discourse account

[Expected result]:
The profile picture from PMO should be displayed as Discourse profile picture

[Actual result]:
System assigned profile picture selected in step 4 is displayed as a profile picture

@LeoMcA

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/DISC-7)

**Comment by LeoMcA** [comment]
Good catch! I think I see what's going on here, fix incoming

**Comment by LeoMcA** [comment]
Fix deployed on https://discourse-staging.itsre-apps.mozit.cloud, can you verify @rleitan?

**Comment by rleitan** [comment]
it's fixed now!
@LeoMcA
