### ISSUE TITLE
Add group setting to watch category by default

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#28]
Upstream RFC: https://meta.discourse.org/t/spec-set-group-default-category-notification-settings/55148

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/DISC-158)

**Comment by LeoMcA** [comment]
Partially worked on in: https://github.com/mozilla/discourse/issues/52

**Comment by Mte90** [comment]
There is a plugin -> https://github.com/amical/discourse-watch-category

**Comment by LeoMcA** [comment]
I've implemented a subset of the upstream spec in https://github.com/mozilla/discourse-group-category-notification which was needed for integration with the community portal.

@Mte90 I think this plugin also satisfies the requirements needed to move the reps-general list to discours

**Comment by Mte90** [comment]
I am not following anymore this feature I will send the news to the reps council

**Comment by Mte90** [comment]
Just checking the code and this doesn't sync with mozillians group.
Maybe it is possible to do it? because right now is quite useless for the reps program.

**Comment by LeoMcA** [comment]
This code doesn't, but we've been long able to sync mozillians (and ldap) groups with discourse using the `discourse-mozilla-iam` plugin - this is how we currently sync the nda group with discourse.

This plugin adds the missing piece to then subscribe a synced group to a category :)

**Comment by hmitsch** [comment]
Hi @LeoMcA and @Mte90, this is a great step forward. I guess we now want to wait for PMO (fka DinoPark) to become available for Community. Once that is done, we can use Mozilla IAM groups to auto-subscribe Mozilla Reps to Discourse categories.

Best regards,
   Henrik

**Comment by LeoMcA** [comment]
Do we need to wait for PMO to be opened to the community and add access groups? We could start right now with Mozillians.org groups

**Comment by data-sync-user** [comment]
➤ Leo McArdle commented:

This has been deployed on prod
