### ISSUE TITLE
Handle email thread forwards/replies

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#57]
_As a user, I want to reply to an existing email thread adding a Discourse category as a new recipient, so that the existing email thread appears as quotes on Discourse._

Currently these quotes get stripped by Discourse so as to ensure that normal email replies to Discourse don't get filled with unnecessary clutter.

One approach to handle this would be to add some logic which determines whether to keep or delete a quote based on whether Discourse already knows about it. Another could be process emails with a subject starting with "Re: \<subject\>" where "\<subject\>" doesn't already exist as a topic in Discourse differently to ones where it does.

A more advanced approach could involve actually creating these quoted emails as Discourse posts, so they appear properly in the interface. This might relate to the existing `enable forwarded emails` feature, or upcoming work in [Discourse 1.9: "Forward multiple emails to Discourse, staging unknown emails as new users and attaching matching existing users by email"](https://meta.discourse.org/t/discourse-version-1-9/61289).

***

https://meta.discourse.org/t/reassure-me-that-staged-users-dont-get-email-summaries-or-mention-notifications/69579/4?u=leomca

**Comment by LeoMcA** [comment]
**Sprint 12 goal:**

Start discussions upstream about implementing this

**Comment by hmitsch** [comment]
Suggestion for iteration 1 scope: Make sure emails from Mozilla's G Suite can be forwarded to Discourse groups (categories). This allows Staff members to forward emails to groups.

**Comment by LeoMcA** [comment]
Posted upstream: https://meta.discourse.org/t/enable-forwarded-emails-doesnt-behave-like-conventional-email-forwarding/111501

**Comment by LeoMcA** [comment]
https://github.com/discourse/discourse/pull/7935

**Comment by LeoMcA** [comment]
[Merged upstream](https://github.com/discourse/discourse/commit/6296ae3d31915f9c521d2b9a04bf2070f501bf82), yet to deploy on our instance

**Comment by LeoMcA** [comment]
Deployed
