### ISSUE TITLE
Send discourse logs to papertrail

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#58]
Send Discourse logs to CloudWatch to be processed, then send alerts on serious errors.

**Comment by TannerFilip** [comment]
What are you wanting the integration to do?

**Comment by LeoMcA** [comment]
> What are you wanting the integration to do?

Alert us when an error appears in the logs (apart from the ones which we know are 'harmless')

**Comment by johngian** [comment]
[] Figure out how to ship logs from discourse
[] Send logs to cloudwatch
[] Create a cloudwatch alarm for discourse errors
[] Create SNS for discourse alerts
[] Integrate SNS /w victorops

**Comment by LeoMcA** [comment]
Discourse logs are being sent to papertrail as part of the new IT-hosted infra
