### ISSUE TITLE
Create MCWS tags

### ISSUE THREAD

**Issue by TomFarrow** [mozilla/discourse#66]
As an MCWS team lead I want to enable tagging so that I can group topics about ownership discussions across categories without creating further, redundant subcategories.

**Comment by LeoMcA** [comment]
As discussed with Tom and Kensie, this should be some sort of permission restricted tag so only they are able to create topics under this tag.

**Comment by LeoMcA** [comment]
@TomFarrow we enabled tagging on Discourse last week.

What tags are required for MCWS?
