### ISSUE TITLE
Migrate to discourse.mozilla.org

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#71]
- [x] [@leo] Check discourse won't set any cookies for mozilla.org or *.mozilla.org
- [x] File DNS change request with WebOps
- [x] Issue certificate https://github.com/mozilla/parsys/issues/212
- [x] Set up discourse.mozilla-community.org -> discourse.mozilla.org redirect

**Comment by LeoMcA** [comment]
> Check discourse won't set any cookies for mozilla.org or *.mozilla.org

Looks like we're good on the cookies front:

![screenshot from 2017-08-01 14-29-04](https://user-images.githubusercontent.com/755354/28830301-df50d41c-76c5-11e7-9a5d-53eabeaac1c5.png)

**Comment by flamingspaz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1386292

**Comment by LeoMcA** [comment]
:tada: https://discourse.mozilla.org/
