### ISSUE TITLE
IT Transition: Send/recieve emails from @discourse.mozilla.org

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#79]
The new plan:

- [x] Write rust email-in lambda https://github.com/mozilla/discourse-email-in-lambda
- [x] Deploy lambda
- [x] Fail when error returned from Discourse
- [ ] Work out what to do with groups

On prod:

- [ ] Create group for notifications@... address
- [x] Install auto-email-in plugin

**During read-only migration phase**

- [x] POP3 should be off on new prod
- [x] Turn POP3 off on old prod
- [x] Migrate DB
- [x] Set up new `notification_email`
- [x] Set up new `reply_by_email_address`, and set old prod reply address in `alternative_reply_by_email_address`
- [x] Turn POP3 on on new prod

**Related discussions**:
- https://meta.discourse.org/t/automatically-set-category-incoming-email-address-based-on-slug/57841

**Comment by leo** [comment]
Heyhoy! Can you guys please stop mis-using my username? Thank you! 😊

**Comment by LeoMcA** [comment]
> Heyhoy! Can you guys please stop mis-using my username? Thank you! 😊

Oh crap, that was total brain fart. Apologies! (And apologies to `Yousef` also)
