### ISSUE TITLE
Integrate metrics from private category with CoSS

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#89]
*As a user considering joining a club, I want to see metrics from the private category which show that lively discussion is taking place, so that I want to join and get access to this special place.*

While doing this, make a list of what pieces of data could be extracted, in order to iterate on this feature in future. The no-brainers are:

- number of users
- time since last activity

**Comment by LeoMcA** [comment]
**Data which can be extracted through the Discourse API:**

- [`https://discourse.mozilla.org/c/{id}/show.json`](https://discourse.mozilla.org/c/198/show.json):
  - Total topic count: `category.topic_count`
  - Total post count (more reflective of activity): `category.post_count`
- [`https://discourse.mozilla.org/c/{id}/none/l/latest.json`](https://discourse.mozilla.org/c/198/none/l/latest.json):
  - Approximated user count (could be called 'active users'): `users.length`
  - Last activity: `topic_list.topics[0].last_posted_at` (with some logic to account for pinned topics).
- [`https://discourse.mozilla.org/categories.json || https://discourse.mozilla.org/categories.json?parent_category_id={parent_id}`](https://discourse.mozilla.org/categories.json):
  - `category_list.categories.find(category => category.id == {id})`:
    - Number of new topics per day: `topics_day`
    - Number of new topics per week: `topics_week`
    - Number of new topics per month: `topics_month`
    - Number of new topics per year: `topics_year`
- [`https://discourse.mozilla.org/admin/reports/topics.json?category_id={id}&start_date={date}&end_date={date}`](https://discourse.mozilla.org/admin/reports/topics.json?category_id=198&start_date=2017-06-14&end_date=2017-07-14):
  - Number of new topics over an arbitrary time-frame: `report.data.reduce((sum, value) => sum + value.y)`
- [`https://discourse.mozilla.org/admin/reports/posts.json?category_id={id}&start_date={date}&end_date={date}`](https://discourse.mozilla.org/admin/reports/posts.json?category_id=198&start_date=2017-06-14&end_date=2017-07-14):
  - Number of new posts over an arbitrary time-frame: `report.data.reduce((sum, value) => sum + value.y)`

Some of the above data is duplicated within those endpoints, so when it comes to implementing this, some sense should be exercised about where to fetch the data from to avoid unnecessary API calls.

**Data which would require a plugin to be extracted**:

- Precise number of users with activity in the category
- Practically anything imaginable which isn't listed above

**Comment by m-branson** [comment]
@LeoMcA Great to see this in today's demo! To push this further in the future, providing users a link/button that directs them to the Discourse group would be super helpful. I realize this is outside the data work you're doing now, just wanted to flag it while it was top of mind. :simple_smile:
