### ISSUE TITLE
Fix upload issue

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#96]
Uploading to Discourse will regularly fail, with the upload counter stuck at 100% and nothing appearing.

Occasionally it will succeed after waiting a while, with the browser also receiving messages about the completed upload of previous attempts.

No errors appear in the Discourse logs or browser console, making me believe this is an S3 issue @flamingspaz.

**Comment by flamingspaz** [comment]
It's either an issue with discourse or the ruby aws sdk, config looks fine to me and I can list objects:
```
[12] pry(main)> s3 = Aws::S3::Resource.new(credentials: Aws::InstanceProfileCredentials.new(), region: 'us-east-1')
=> #<Aws::S3::Resource>
[13] pry(main)> bucket = s3.bucket('discourse-paas-staging-uploads')
=> #<Aws::S3::Bucket name="discourse-paas-staging-uploads">
[14] pry(main)> bucket = s3.bucket('discourse-paas-staging-content')
=> #<Aws::S3::Bucket name="discourse-paas-staging-content">
[15] pry(main)> bucket.objects().collect(&:key)
=> ["1000d84e4f1d2c9bab5b1d2a68d59863dfb8bc1135d4_120x120.png",
 "1001b348aa565a8d364ef32aef6a71dae607d086d2cb_45x45.png",
 "1002d9349b64691167f14101f5e35296f70c21b505be_45x45.png",
 "1003fb8a4b72505438fc615e063f245a508e29305f98_25x25.png",
```

**Comment by grahamperrin** [comment]
If it helps: a few days I was slightly surprised by the JPEG result of a `.png` upload. Is that intended, in some situations?

**Comment by LeoMcA** [comment]
@grahamperrin yeah, discourse converts uploaded pngs to jpeg and if the jpeg is smaller uses that instead

**Comment by grahamperrin** [comment]
For comparison purposes, a pause at '100%' was apparent with the second of four uploads at (volatile) https://try.discourse.org/t/upload-issue-affecting-mozilla-discourse-a-comparison/836

![2017-09-14 04 48 37](https://user-images.githubusercontent.com/192271/30411421-b21b877a-9908-11e7-8a5b-838767123928.png)

![2017-09-14 04 48 59](https://user-images.githubusercontent.com/192271/30411417-ae8c5f62-9908-11e7-99c8-e9f6cf6c7300.png)

**Comment by grahamperrin** [comment]
With apologies for bumping: this issue is a significant hindrance. 

Can I do anything to help?

**Comment by LeoMcA** [comment]
> With apologies for bumping: this issue is a significant hindrance.

No problem, I'm having another crack at working out what's causing this bug.

> Can I do anything to help?

If you've noticed any pattern to how/if/when uploads fail (and how) and when they succeed that may prove useful.

**Comment by LeoMcA** [comment]
Looks like this isn't an upload issue, but a MessageBus issue. Posted upstream here: https://meta.discourse.org/t/messagebus-misconfiguration/70508

**Comment by LeoMcA** [comment]
@grahamperrin uploads are working fine for me now. Can you confirm they're working for you too?

**Comment by LeoMcA** [comment]
Short polling issues fixed upstream: https://meta.discourse.org/t/messagebus-short-polling-is-not-working/70508/12?u=leomca

Will rebuild prod and then close this issue.

**Comment by grahamperrin** [comment]
> … working for you too?

I think so, thanks! 

As a simple test, I edited two screenshots into https://discourse.mozilla.org/t/-/17087/60?u=grahamperrin
